CREATE TABLE IF NOT EXISTS ingestion_data (
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  temp FLOAT NOT NULL,
  feels_like FLOAT NOT NULL,
  temp_min FLOAT NOT NULL,
  temp_max FLOAT NOT NULL,
  pressure INT NOT NULL,
  humidity INT NOT NULL,
  sea_level INT NOT NULL,
  grnd_level INT NOT NULL,
  visibility INT NOT NULL,
  wind_speed FLOAT NOT NULL,
  wind_deg FLOAT NOT NULL,
  clouds INT NOT NULL,
  weather_main TEXT NOT NULL,
  weather_description TEXT NOT NULL,
  sunrise BIGINT NOT NULL,
  sunset BIGINT NOT NULL,
  city_name TEXT NOT NULL,
  ingestion_timestamp BIGINT NOT NULL,
  data_source TEXT NOT NULL
);