CREATE TABLE IF NOT EXISTS weather_ingestion_data (
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  temp FLOAT NOT NULL,
  feels_like FLOAT NOT NULL,
  temp_min FLOAT NOT NULL,
  temp_max FLOAT NOT NULL,
  pressure INT NOT NULL,
  humidity INT NOT NULL,
  sea_level INT NOT NULL,
  grnd_level INT NOT NULL,
  visibility INT NOT NULL,
  wind_speed FLOAT NOT NULL,
  wind_deg FLOAT NOT NULL,
  clouds INT NOT NULL,
  weather_main TEXT NOT NULL,
  weather_description TEXT NOT NULL,
  sunrise BIGINT NOT NULL,
  sunset BIGINT NOT NULL,
  city_name TEXT NOT NULL,
  ingestion_timestamp BIGINT NOT NULL,
  data_source TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS air_quality_ingestion_data (
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  lat FLOAT NOT NULL,
  long FLOAT NOT NULL,
  aqi SMALLINT NOT NULL,
  co DOUBLE PRECISION NOT NULL,
  no DOUBLE PRECISION NOT NULL,
  no2 DOUBLE PRECISION NOT NULL,
  o3 DOUBLE PRECISION NOT NULL,
  so2 DOUBLE PRECISION NOT NULL,
  pm2_5 DOUBLE PRECISION NOT NULL,
  pm10 DOUBLE PRECISION NOT NULL,
  nh3 DOUBLE PRECISION NOT NULL,
  city_name TEXT NOT NULL,
  ingestion_timestamp BIGINT NOT NULL,
  data_source TEXT NOT NULL
)